import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CartProvider from '@/components/Providers';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CartProvider>

    <ClerkProvider>
      <html lang="en">
        <SignedOut>
          <SignInButton />
        </SignedOut>
    
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
    </CartProvider>
  );
}
